apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-node-server
spec:
  selector:
    matchLabels:
      app: simple-node-server
  template:
    metadata:
      labels:
        app: simple-node-server
    spec:
      containers:
        - name: simple-node-server
          image: smartsameer/node_server:3.0
          ports:
            - containerPort: 4000
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
