apiVersion: v1
kind: Service
metadata:
  name: simple-node-server-service
spec:
  selector:
    app: simple-node-server
  type: ClusterIP
  ports:
    - port: 4000
      protocol: TCP
      targetPort: 4000
