apiVersion: v1
kind: Service
metadata:
  name: simple-node-server-service
spec:
  type: NodePort
  selector:
    app: simple-node-server
  ports:
    - port: 4000
      protocol: TCP
      targetPort: 4000
      nodePort: 32000
